import React, { useEffect, useMemo, useState } from 'react';
import { SchoolClass, Student, Role } from '../types';
import { Building2, Users, Plus, Pencil, Trash2, Search, GraduationCap, UserRound, X } from 'lucide-react';

type Teacher = { id:string; name:string; employeeId:string; subject:string; phone:string; email:string; assignedClass:string; assignedSection:string; };
interface Props { classes:SchoolClass[]; students:Student[]; selectedStudent:Student; currentRole:Role; isHindi:boolean; onSelectStudent:(s:Student)=>void; onAddNewSection:(c:SchoolClass)=>void; onNavigateToTab:(t:string)=>void; onStudentsChange?:(s:Student[])=>void; onClassesChange?:(c:SchoolClass[])=>void; }
const SK='edu_students_v1', CK='edu_classes_v1', TK='edu_teachers_v1';
const blankStudent=(c='Class 1',s='A'):Student=>({id:'',name:'',rollNo:'',admissionNo:'',class:c,section:s,academicYear:'2026-27',avatar:'',dob:'',gender:'',bloodGroup:'',attendancePercentage:100,parentName:'',parentRelation:'Father',parentPhone:'',parentEmail:'',address:'',busRoute:'',emergencyContact:'',classTeacher:{name:'',subject:'',phone:'',email:'',avatar:''},subjects:[]});
const blankTeacher=():Teacher=>({id:'',name:'',employeeId:'',subject:'',phone:'',email:'',assignedClass:'',assignedSection:''});

export const ClassSectionManager:React.FC<Props>=({classes,students,selectedStudent,isHindi,onSelectStudent,onAddNewSection,onNavigateToTab,onStudentsChange,onClassesChange})=>{
 const [tab,setTab]=useState<'classes'|'students'|'teachers'>('classes');
 const [ls,setLs]=useState(students),[lc,setLc]=useState(classes),[teachers,setTeachers]=useState<Teacher[]>([]);
 const [q,setQ]=useState(''),[filter,setFilter]=useState(''),[modal,setModal]=useState<'student'|'class'|'teacher'|null>(null),[edit,setEdit]=useState('');
 const [sf,setSf]=useState<Student>(blankStudent()),[cf,setCf]=useState({className:'Class 1',section:'A',roomNo:'',capacity:40,wing:'Primary' as SchoolClass['wing'],classTeacherName:'',classTeacherSubject:''}),[tf,setTf]=useState<Teacher>(blankTeacher());
 useEffect(()=>{try{const s=localStorage.getItem(SK);if(s)setLs(JSON.parse(s));const c=localStorage.getItem(CK);if(c)setLc(JSON.parse(c));const t=localStorage.getItem(TK);if(t)setTeachers(JSON.parse(t));}catch{}},[]);
 const ps=(v:Student[])=>{setLs(v);localStorage.setItem(SK,JSON.stringify(v));onStudentsChange?.(v)}, pc=(v:SchoolClass[])=>{setLc(v);localStorage.setItem(CK,JSON.stringify(v));onClassesChange?.(v)}, pt=(v:Teacher[])=>{setTeachers(v);localStorage.setItem(TK,JSON.stringify(v))};
 useEffect(()=>{if(!localStorage.getItem(SK))localStorage.setItem(SK,JSON.stringify(students));if(!localStorage.getItem(CK))localStorage.setItem(CK,JSON.stringify(classes));},[students,classes]);
 const filtered=useMemo(()=>ls.filter(s=>(!filter||s.class===filter)&&(!q||[s.name,s.admissionNo,s.rollNo,s.parentName,s.class,s.section].join(' ').toLowerCase().includes(q.toLowerCase()))),[ls,filter,q]);
 const openStudent=(s?:Student)=>{setEdit(s?.id||'');setSf(s?{...s}:blankStudent(lc[0]?.className||'Class 1',lc[0]?.section||'A'));setModal('student')};
 const openClass=(c?:SchoolClass)=>{setEdit(c?.id||'');setCf(c?{className:c.className,section:c.section,roomNo:c.roomNo,capacity:c.capacity,wing:c.wing,classTeacherName:c.classTeacherName,classTeacherSubject:c.classTeacherSubject}:{className:'Class 1',section:'A',roomNo:'',capacity:40,wing:'Primary',classTeacherName:'',classTeacherSubject:''});setModal('class')};
 const openTeacher=(t?:Teacher)=>{setTf(t?{...t}:blankTeacher());setModal('teacher')};
 const saveStudent=(e:React.FormEvent)=>{e.preventDefault();if(!sf.name.trim())return;const v=sf.id?ls.map(s=>s.id===sf.id?sf:s):[...ls,{...sf,id:'stu-'+Date.now()}];ps(v);setModal(null)};
 const saveClass=(e:React.FormEvent)=>{e.preventDefault();const id=edit||'cls-'+Date.now(),sec=cf.section.toUpperCase(),old=lc.find(c=>c.id===edit);const v:SchoolClass={id,className:cf.className,section:sec,roomNo:cf.roomNo,classTeacherName:cf.classTeacherName,classTeacherSubject:cf.classTeacherSubject,classTeacherAvatar:old?.classTeacherAvatar,totalStudents:ls.filter(s=>s.class===cf.className&&s.section===sec).length,capacity:Number(cf.capacity)||40,wing:cf.wing,schedule:old?.schedule||[]};pc(edit?lc.map(c=>c.id===edit?v:c):[...lc,v]);setModal(null);onAddNewSection(v)};
 const saveTeacher=(e:React.FormEvent)=>{e.preventDefault();if(!tf.name.trim())return;const v=tf.id?teachers.map(t=>t.id===tf.id?tf:t):[...teachers,{...tf,id:'tch-'+Date.now()}];pt(v);setModal(null)};
 const del=(kind:string,id:string)=>{if(!confirm('Delete this record?'))return;if(kind==='s')ps(ls.filter(x=>x.id!==id));else if(kind==='c')pc(lc.filter(x=>x.id!==id));else pt(teachers.filter(x=>x.id!==id))};
 return <div className="space-y-6">
  <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-xs"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><span className="p-2 rounded-xl bg-purple-100 text-purple-700"><Building2 className="w-5 h-5"/></span><h2 className="text-xl font-bold">School Master Management</h2></div><p className="text-sm text-slate-500 mt-1">Add, edit and manage Students, Teachers, Classes and Sections.</p></div><div className="flex gap-2 flex-wrap"><button onClick={()=>openStudent()} className="px-4 py-2.5 rounded-xl bg-indigo-600 text-white font-bold flex gap-2 items-center"><Plus className="w-4 h-4"/>Student</button><button onClick={()=>openTeacher()} className="px-4 py-2.5 rounded-xl bg-emerald-600 text-white font-bold flex gap-2 items-center"><Plus className="w-4 h-4"/>Teacher</button><button onClick={()=>openClass()} className="px-4 py-2.5 rounded-xl bg-purple-600 text-white font-bold flex gap-2 items-center"><Plus className="w-4 h-4"/>Class / Section</button></div></div>
  <div className="flex gap-2 mt-6 border-t pt-4">{(['classes','students','teachers'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-2 rounded-xl text-sm font-bold ${tab===x?'bg-slate-900 text-white':'bg-slate-100'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></div>
  {tab==='classes'&&<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{lc.map(c=><div key={c.id} className="bg-white rounded-2xl border p-5"><div className="flex justify-between"><div><span className="text-xs font-bold text-purple-700">{c.wing}</span><h3 className="text-xl font-black">{c.className} — {c.section}</h3><p className="text-xs text-slate-500">{c.roomNo||'Room not assigned'} • {ls.filter(s=>s.class===c.className&&s.section===c.section).length}/{c.capacity}</p></div><div className="flex gap-1"><button onClick={()=>openClass(c)} className="p-2 bg-slate-100 rounded-lg"><Pencil className="w-4 h-4"/></button><button onClick={()=>del('c',c.id)} className="p-2 bg-red-50 text-red-600 rounded-lg"><Trash2 className="w-4 h-4"/></button></div></div><div className="mt-4 p-3 rounded-xl bg-purple-50"><b>{c.classTeacherName||'No class teacher'}</b><p className="text-xs text-purple-700">{c.classTeacherSubject}</p></div><button onClick={()=>{setFilter(c.className);setTab('students')}} className="mt-3 text-xs font-bold text-indigo-600">View students →</button></div>)}</div>}
  {tab==='students'&&<div className="bg-white rounded-2xl border p-5"><div className="flex gap-3 mb-4"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student, admission no, parent..." className="w-full pl-9 p-2.5 border rounded-xl"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="px-3 rounded-xl border"><option value="">All Classes</option>{Array.from(new Set(lc.map(c=>c.className))).map(c=><option key={c}>{c}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b"><th className="p-3">Student</th><th>Admission</th><th>Class</th><th>Parent / Mobile</th><th>Actions</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} className="border-b"><td className="p-3 font-bold">{s.name}</td><td>{s.admissionNo}</td><td>{s.class}-{s.section}</td><td>{s.parentName}<br/><span className="text-xs">{s.parentPhone}</span></td><td><button onClick={()=>onSelectStudent(s)} className="px-2 py-1 mr-1 text-xs rounded bg-indigo-50 text-indigo-700">Open</button><button onClick={()=>openStudent(s)} className="p-2 bg-slate-100 rounded"><Pencil className="w-4 h-4"/></button><button onClick={()=>del('s',s.id)} className="p-2 ml-1 bg-red-50 text-red-600 rounded"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></div>}
  {tab==='teachers'&&<div className="bg-white rounded-2xl border p-5"><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{teachers.map(t=><div key={t.id} className="border rounded-2xl p-4"><div className="flex justify-between"><div><h3 className="font-bold">{t.name}</h3><p className="text-xs text-slate-500">{t.employeeId} • {t.subject}</p></div><div><button onClick={()=>openTeacher(t)} className="p-2 bg-slate-100 rounded"><Pencil className="w-4 h-4"/></button><button onClick={()=>del('t',t.id)} className="p-2 ml-1 bg-red-50 text-red-600 rounded"><Trash2 className="w-4 h-4"/></button></div></div><p className="text-xs mt-3">{t.phone} • {t.email}</p><p className="text-xs font-bold text-emerald-700 mt-2">{t.assignedClass}-{t.assignedSection}</p></div>)}</div></div>}
  {modal&&<div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto p-6"><div className="flex justify-between mb-5"><h3 className="text-xl font-black">{modal==='student'?(edit?'Edit Student':'Add Student'):modal==='class'?(edit?'Edit Class / Section':'Add Class / Section'):(edit?'Edit Teacher':'Add Teacher')}</h3><button onClick={()=>setModal(null)}><X/></button></div>
  {modal==='student'&&<form onSubmit={saveStudent} className="grid md:grid-cols-2 gap-3">{([['name','Student Name'],['admissionNo','Admission No'],['rollNo','Roll No'],['dob','DOB'],['gender','Gender'],['parentName','Parent Name'],['parentPhone','Parent Mobile'],['parentEmail','Parent Email'],['address','Address']] as const).map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input required={k==='name'} value={String(sf[k])} onChange={e=>setSf({...sf,[k]:e.target.value})} className="mt-1 w-full p-2.5 border rounded-xl font-normal"/></label>)}<label className="text-xs font-bold">Class<select value={sf.class} onChange={e=>setSf({...sf,class:e.target.value})} className="mt-1 w-full p-2.5 border rounded-xl">{Array.from(new Set(lc.map(c=>c.className))).map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs font-bold">Section<select value={sf.section} onChange={e=>setSf({...sf,section:e.target.value})} className="mt-1 w-full p-2.5 border rounded-xl">{lc.filter(c=>c.className===sf.class).map(c=><option key={c.section}>{c.section}</option>)}</select></label><div className="md:col-span-2 flex justify-end"><button className="px-5 py-2.5 bg-indigo-600 text-white rounded-xl font-bold">Save Student</button></div></form>}
  {modal==='class'&&<form onSubmit={saveClass} className="grid md:grid-cols-2 gap-3">{([['className','Class Name'],['section','Section'],['roomNo','Room No'],['classTeacherName','Class Teacher'],['classTeacherSubject','Teacher Subject']] as const).map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input value={String(cf[k])} onChange={e=>setCf({...cf,[k]:e.target.value})} className="mt-1 w-full p-2.5 border rounded-xl font-normal"/></label>)}<label className="text-xs font-bold">Capacity<input type="number" value={cf.capacity} onChange={e=>setCf({...cf,capacity:Number(e.target.value)})} className="mt-1 w-full p-2.5 border rounded-xl"/></label><label className="text-xs font-bold">Wing<select value={cf.wing} onChange={e=>setCf({...cf,wing:e.target.value as SchoolClass['wing']})} className="mt-1 w-full p-2.5 border rounded-xl">{['Primary','Middle','Secondary','Senior Secondary'].map(x=><option key={x}>{x}</option>)}</select></label><div className="md:col-span-2 flex justify-end"><button className="px-5 py-2.5 bg-purple-600 text-white rounded-xl font-bold">Save Class / Section</button></div></form>}
  {modal==='teacher'&&<form onSubmit={saveTeacher} className="grid md:grid-cols-2 gap-3">{([['name','Teacher Name'],['employeeId','Employee ID'],['subject','Subject'],['phone','Mobile'],['email','Email'],['assignedClass','Assigned Class'],['assignedSection','Assigned Section']] as const).map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input required={k==='name'} value={String(tf[k])} onChange={e=>setTf({...tf,[k]:e.target.value})} className="mt-1 w-full p-2.5 border rounded-xl font-normal"/></label>)}<div className="md:col-span-2 flex justify-end"><button className="px-5 py-2.5 bg-emerald-600 text-white rounded-xl font-bold">Save Teacher</button></div></form>}</div></div>}
 </div>;
};